<?php

namespace App\Math;

use App\Utils\Stack;

class ExpressionUnitStack extends Stack
{
    /**
     * @param IExpressionUnit $value
     * @return int
     * @throws \Exception
     */
    public function push($value): int
    {
        if (! ($value instanceof IExpressionUnit) ) {
            throw new \Exception('Некорректная операция');
        }
        return parent::push($value);
    }

    /**
     * @return IExpressionUnit
     */
    public function pop(): mixed
    {
        return parent::pop(); // TODO: Change the autogenerated stub
    }
}